name: Branch
on:
  pull_request:
    branches:
      - main
      - release/**
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - release/v*
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'examples/**'
      - 'test/**'
      - 'README.md'

permissions:
  contents: write
  actions: write

jobs:
  github-action:
    uses: cloudposse/.github/.github/workflows/shared-github-action.yml@main
    secrets: inherit
