name: Feature branch
on:
  pull_request:
    branches:
      - main
      - release/v*
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  actions: write

jobs:
  perform:
    uses: cloudposse/github-actions-workflows-github-action-composite/.github/workflows/feature-branch.yml@main
    secrets: inherit
