name: Release
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: write

jobs:
  perform:
    uses: cloudposse/github-actions-workflows-github-action-composite/.github/workflows/release.yml@main
    secrets: inherit
